#pragma once

#define GAME_TITLE "Game"
#define FPS_60 0.016F

// Window settings
#define WINDOW_SIZE_WIDTH 800.0F
#define WINDOW_SIZE_HEIGHT 600.0F
#define WINDOW_ASPECT_RATIO 1.33F
#define JOYSTICK_DEAD_ZONE_LOWER 0.2

// Render setting
#define STAR_FIELD_SIZE 1000

// Game Dimensions
#define FOV 0.872665F // 50 degrees in radians
#define CAMERA_TRUCK_SPEED 0.5F
#define CAMERA_PEDESTAL_SPEED 0.5F
#define CAMERA_MAX_TRUCK 40.0F
#define CAMERA_MAX_PEDESTAL 35.0F
#define WORLD_SIZE_WIDTH 120.0F
#define WORLD_SIZE_HEIGHT 90.0F
#define WORLD_DEATH_COOL_DOWN 2.0F
#define PLAYER_RADIUS 2.0F
#define PLAYER_BOUNDARY 0.5F
#define BULLET_SPREAD 0.3F
#define BULLET_RADIUS 1.6F
#define CHASER_ENEMY_RADIUS 3.5F
#define SIMPLE_ENEMY_RADIUS 5.0F

// Game mechanics
#define DECELERATION 230.0F
#define ACCELERATION 250.0F
#define PLAYER_MAX_VELOCITY 90.0F
#define PLAYER_MAX_VELOCITY_THRESHOLD 0.8F
#define BULLET_MAX_VELOCITY 170.0F
#define ENEMY_MAX_VELOCITY 40.0F
#define PLAYER_BULLET_COOL_DOWN 0.1F
#define SIMPLE_ENEMY_MIN_ROTATION_SPEED 0.8F
#define SIMPLE_ENEMY_MAX_ROTATION_SPEED 1.2F
#define SIMPLE_ENEMY_VELOCITY 30.F

// Enemy Spawn Constants
#define SPAWN_ENEMIES true
#define WORLD_ENEMY_COOL_DOWN 0.2F
#define RANDOM_SPAWN_PLAYER_SAFE_ZONE_RADIUS 50.0F

// Shader UniForms
#define PROJECTION_MATRIX "projectionMatrix"
#define VIEW_MATRIX "viewMatrix"
#define MODEL_MATRIX "modelMatrix"
#define OBJECT_COLOR "objectColor"
